python:main.py",\n            "print('Hello, World!')",\n            "
",\n            "print('Hello, World!')",\n            "
python",\n            "print('Hello, World!')",\n            "
python:example.py",\n            "import os",\n            "print('Hello, World!')",\n            "
",\n            "print('Do not replace')",\n            "
python:main.py",\n            "print('Hello, World!')",\n            "
python:example.py",\n            "import os",\n            "print('Hello, World!')",\n            "
",\n            "print('Do not replace')",\n            "